### ISSUE TITLE
add ci: auto build and test when pushed to github

### ISSUE THREAD

**Issue by williamfzc** [quickappcn/sample#9]
**Is your feature request related to a problem? Please describe.**

> 作为一个demo工程，没有持续集成与单元测试是非常奇怪的。这导致这个工程的质量很难量化，而开发者也无从了解这个工程是否处于可用状态。

**Describe the solution you'd like**

> 严格的单元测试可能不太现实，但是在每次提交后进行一次rpk打包应该是完全可行且非常容易实现的（travis、circle均可）。打包过程可以及时发现编译层面的错误，开发者也能够直接下载并使用release出来的rpk包而无需本地环境。

**Describe alternatives you've considered**

> 以travis为例，加入travis.yml即可实现。[travis文档](https://travis-ci.org/dashboard)

**Additional context**

**Comment by diydyq** [comment]
谢谢反馈；当前已增加circleci的能力；
后面将增加两方面能力：
1) 支持分支/每次提交时，构建rpk并可以下载的能力；
2) 增加项目可测试的能力（手机上运行单测/集成测试）；
欢迎提出更多反馈；
